<form action="<?php echo $block->getUrl('formfetch/form/submit') ?>" method="post">
    <fieldset>
        <legend>Custom Form</legend>
            <label for="email">Email:</label>
            <input type="text" name="email" id="email" required />
        <br>
        <br>
            <label for="first_name">First Name:</label>
            <input type="text" name="first_name" id="first_name" required />
        <br>
        <br>
            <label for="last_name">Last Name:</label>
            <input type="text" name="last_name" id="last_name" required />
        <br>
        <br>
            <label for="school_name">School Name:</label>
            <input type="text" name="school_name" id="school_name" required />
        <br>
        <br>
            <button type="submit">Submit</button>
    </fieldset>
</form>
